version: "2"

services:
  data:
    image: busybox
    container_name: "durak_data"
    volumes:
      - /data

  redis:
    image: redis:3.0.7
    container_name: "durak_redis"
    ports:
      - 6379
    volumes_from:
      - data

  mysql:
    image: mysql:5.7
    container_name: "durak_mysql"
    ports:
      - 3306:3306
    env_file:
      - ./docker/mysql/.env
    volumes_from:
      - data

  phpmyadmin:
    container_name: myadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:8888
    links:
      - "mysql:mysql"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306

  front:
    image: abiosoft/caddy
    container_name: "durak_caddy"
    environment:
      - CADDYPATH=/etc/caddycerts
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/Caddyfile
      - ./docker/caddy/caddyssl:/etc/caddycerts
    depends_on:
      - app
    volumes_from:
      - app

  app:
    image: durak_skeleton:build
    build: .
    container_name: "durak_app"
    volumes:
      - .:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - mysql
      - redis
    command: /usr/local/sbin/php-fpm --allow-to-run-as-root

  websockets:
    image: durak_skeleton:build
    build: .
    container_name: "durak_websockets"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - app
    command: /usr/local/bin/scheduler-nodejs
